name: Upload to S3

on:
  push:
    branches: [ main ]

jobs:
  upload:
    runs-on: ubuntu-latest

    # This is crucial - it allows the action to get temporary credentials 
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::226290659649:role/s3_connectgithub
        aws-region: us-east-1

      # 2. Download from S3 to runner
    - name: Download from S3
      run: |
          aws s3 sync s3://s3galle/ ./downloaded-code --delete
          
      # 3. Transfer files to Server
    - name: Transfer to Server via SCP/Rsync
      uses: appleboy/scp-action@v0.1.7
      with:
          host: 13.219.96.18    
          username: ubuntu
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./downloaded-code/*"
          target: "/var/www/example.com"
          strip_components: 1 # Optional: Removes top-level folder

