name: Deploy HTML website

on:
  push:
    branches:
      - main # Triggers the workflow on push events to the main branc
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up temporary files
        run: sudo rm -rf /tmp/*
