name: Deploy Code from S3 to EC2  
on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH and Role Access  
        uses: appleboy/ssh-action@master
        with:
          host: 13.219.96.18    
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Sync code from S3 to local folder
            # The EC2 instance automatically uses its attached IAM Role
            aws s3 sync s3://s3galle/ /var/www/example.com/ --delete
            
           
